version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
resolve_s3 = true
image_repositories = []

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "resCP14Yapy-staging"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
resolve_s3 = true
image_repositories = []

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "resCP14Yapy-production"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
resolve_s3 = true
image_repositories = []
